name: CD sans kybernetes

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verifier que app.js existe et est bien valide
        run: node --check app.js

  build-and-push:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

    #dockerhub login

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t evanslmntrix/mon-app:${{ github.sha }} .
          docker push evanslmntrix/mon-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: checkout du gitops repo
        uses: actions/checkout@v4
        with:
          repository: 'Lmntrixo/gitops-argocd'
          token: ${{ secrets.GITOPS_GITHUB_TOKEN }}

     #automatic modification of the tag on manifest file

      - name: update Image Tag in Deployment YAML
          run: |
            sed -i 's|image: evanslmntri/mon-app:.*|image: evanslmntrix/mon-app:${{ github.sha }}|g' deployment.yaml

    # pushing changes on gitops repos
      - name: commit and push on gitops repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add deployment.yaml
          git commit -m "chore: up image to ${{ github.sha }} [skip ci]" || echo "no changes to commit"
          git push origin main


