name: CD sans kybernetes

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verifier que app.js existe et est bien valide
        run: node --check app.js

  build-and-push:
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t evanslmntrix/mon-app:${{ github.sha }} .
          docker push evanslmntrix/mon-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: deployer sur kubernetes( kind)
        run: kubectl set image deployment/mon-app mon-app=evanslmntrix/mon-app:${{ github.sha }}


